# Generated by Django 6.0.2 on 2026-02-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('profile', 'Profile'), ('education', 'Education'), ('experience', 'Experience'), ('project', 'Project'), ('publication', 'Publication'), ('skill', 'Skill')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, help_text='HTML allowed')),
                ('date_start', models.CharField(blank=True, max_length=50)),
                ('date_end', models.CharField(blank=True, max_length=50)),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated', max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', '-date_start'],
            },
        ),
    ]
